// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkaRnP3uYye2lr4KPJQW-eddfaC8tH6J4',
    appId: '1:99387092651:android:b18ad09d2b68ec50b551ee',
    messagingSenderId: '99387092651',
    projectId: 'girdharipos',
    storageBucket: 'girdharipos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYKPvQJnH3UkkOJDqyrDQnmirY6F1DylE',
    appId: '1:99387092651:ios:e93b824f60b92477b551ee',
    messagingSenderId: '99387092651',
    projectId: 'girdharipos',
    storageBucket: 'girdharipos.appspot.com',
    iosBundleId: 'com.example.girdhari',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZckq1J32XakCWtTvox7yomG359ZO364',
    appId: '1:99387092651:web:e4ad74448ac9a947b551ee',
    messagingSenderId: '99387092651',
    projectId: 'girdharipos',
    authDomain: 'girdharipos.firebaseapp.com',
    storageBucket: 'girdharipos.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYKPvQJnH3UkkOJDqyrDQnmirY6F1DylE',
    appId: '1:99387092651:ios:e93b824f60b92477b551ee',
    messagingSenderId: '99387092651',
    projectId: 'girdharipos',
    storageBucket: 'girdharipos.appspot.com',
    iosBundleId: 'com.example.girdhari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfZckq1J32XakCWtTvox7yomG359ZO364',
    appId: '1:99387092651:web:427db9959078ad02b551ee',
    messagingSenderId: '99387092651',
    projectId: 'girdharipos',
    authDomain: 'girdharipos.firebaseapp.com',
    storageBucket: 'girdharipos.appspot.com',
  );
}
